### ISSUE TITLE
Executable for windows 

### ISSUE THREAD

**Issue by wgranados** [bhowmikp/Password_Generator#2]
I don't know what python is, and I only know how to run .exe files. 
Please, I just want to make a secure password :)))

**Comment by bhowmikp** [comment]
I have created a linux executable. All executables need to be generated in their particular operating system. 

You should be able to run password_generator_gui.py by default on mac since python is installed by default

As for windows you have to install python to run the gui file.

**Comment by bhowmikp** [comment]
I have created a windows and linux executable in a folder called ```executable```. Hopefully that helps
